version: "3.9"

services: 
  db:
    image: postgres
    restart: always
    ports: 
      - 5438:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes: 
      - ./tmp/db:/var/lib/postgresql/data      
  app:
    build: .
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    depends_on: 
      - db
    
 
  